[package]
name = "rustracer"
version = "0.1.0"
authors = ["Alexandru Pana <astronothing@gmail.com>"]

[dependencies]
rand = "0.3"
crossbeam = "0.2"
time = "0.1"
scoped-pool = "1"

[dependencies.clap]
version = "2"
default-features = false